swipe:
  3:
    left:
      command: 'xdotool key super+Left'
    right:
      command: 'xdotool key super+Right'
    up:
      command: 'xdotool key ctrl+alt+Down'
    down:
      command: 'xdotool key ctrl+alt+Up'
pinch:
  2:
    in:
      command: 'xdotool key super+Up'
    out:
      command: 'xdotool key super+Down'
threshold:
  swipe: 0.3
  pinch: 0.1
interval:
  swipe: 1
  pinch: 1

