import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 5

dimensions.columns = 120
dimensions.lines = 32

decorations = "Buttonless"

opacity = 0.70
blur = true

option_as_alt = "Both"

[font]
normal.family = "Hack Nerd Font"
normal.style = "Regular"

offset.x = 1
offset.y = 1

size = 15

[scrolling]
history = 10000
multiplier = 3

[cursor]
style = "Block"

[mouse]
hide_when_typing = true
